name: Deploy Proxy Server

on:
  push:
    branches:
      - main  # 监听 main 分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v3

    - name: 设置 Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "18"

    - name: 安装依赖
      run: npm install express axios cors

    - name: 运行服务器
      run: node proxy.js
